POST  http://localhost:8000/api/auth/register
Content-Type: application/json

{   
    "username":"phat",
    "email":"phat@gmail.com",
    "password":"12345678"
}

###
POST  http://localhost:8000/api/auth/login
Content-Type: application/json

{   
   
    "email":"phat@gmail.com",
    "password":"12345678"
}

###

PUT  http://localhost:8000/user/update/6631ae6ab7b243d4153c414a
Content-Type: application/json

{
   "username": "phat2",
}

###
